矩阵相乘

In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
np.dot(A,B)


array([[19, 22],
       [43, 50]])

简易神经网络

In [2]:
import numpy as np
#激活函数
def sigmoid(x):
    return 1/(1+np.exp(-x))
x=np.random.randn(10,2)
w1=np.random.randn(2,4)
b1=np.random.randn(4)
w2=np.random.randn(4,3)
b2=np.random.randn(3)
h=np.dot(x,w1)+b1
a=sigmoid(h)
s=np.dot(a,w2)+b2
print(s)

[[-1.14345992  0.54889011 -3.73831465]
 [-1.26640778  0.35650041 -4.22274817]
 [-1.10796359  0.60462812 -3.6882283 ]
 [-1.61480016  0.45013333 -3.13112048]
 [-1.31779295  0.48006698 -3.61052249]
 [-1.11492334  0.57637767 -3.73616732]
 [-1.1652464   0.56025786 -3.62386562]
 [-1.10564029  0.61229222 -3.64969169]
 [-1.62074761  0.16644719 -4.29003269]
 [-1.10759546  0.61512896 -3.66120914]]
