<span style="color:orange;">语料库预处理</span>

In [3]:
import numpy as np
def preprocess(txt):
    txt=txt.lower()
    txt=txt.replace("."," .")
    words=txt.split(" ")
    id_to_word={}
    word_to_id={}
    for word in words:
        if word not in word_to_id:
            id_to_word[len(word_to_id)]=word
            word_to_id[word]=len(word_to_id)
    corpus=np.array([word_to_id[word] for word in words])
    return corpus,word_to_id,id_to_word

In [5]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
print("corpus:", corpus)
print("word_to_id:", word_to_id)
print("id_to_word:", id_to_word)

corpus: [0 1 2 3 4 1 5 6]
word_to_id: {'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}
id_to_word: {0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


<span style="color:orange;">共现矩阵</span>

In [6]:
def create_co_matrix(corpus, vocab_size, window_size=1):
    corpus_size = len(corpus)
    co_matrix = np.zeros((vocab_size, vocab_size), dtype=np.int32)
    for idx, word_id in enumerate(corpus):
        for i in range(1, window_size + 1):
            left_idx = idx - i
            right_idx = idx + i
            if left_idx >= 0:
                left_word_id = corpus[left_idx]
                co_matrix[word_id, left_word_id] += 1
            if right_idx < corpus_size:
                right_word_id = corpus[right_idx]
                co_matrix[word_id, right_word_id] += 1
    return co_matrix

In [7]:
print("co_matrix:", create_co_matrix(corpus, len(word_to_id), window_size=1))

co_matrix: [[0 1 0 0 0 0 0]
 [1 0 1 0 1 1 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 1 0 0 0]
 [0 1 0 0 0 0 1]
 [0 0 0 0 0 1 0]]
